version: '3.8'

services:
  nextjs:
    build: .
    container_name: nextjs_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - traefik_web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`portfolio.${DOMAIN}`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=myresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_web"

networks:
  traefik_web:
    external: true
    name: traefik_web